# Generated by Django 4.2.20 on 2025-03-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='contact',
        ),
    ]
